const E_NOVEL_EVENT = {
    GET_LIST: 'GET_LIST',
    GET_CHAPTER_LIST: 'GET_CHAPTER_LIST',
    GET_CHAPTER_INFO: 'GET_CHAPTER_INFO',
    SEARCH: 'SEARCH',
    DOWNLOAD: 'DOWNLOAD',
}

module.exports = E_NOVEL_EVENT
